# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af33583dacfa9c724fe6a66740f909da"
application_url = "https://cardora.unbundl.com/app"
embedded = true
name = "Cardora - Gift Card Manager"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_gift_cards, write_gift_cards"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [
    "customers/redact",
    "customers/data_request",
    "shop/redact"
  ]
  uri = "/webhooks/compliance"

[auth]
redirect_urls = [ "https://cardora.unbundl.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
